### ISSUE TITLE
zmenil sa format RTVS archivu

### ISSUE THREAD

**Issue by hudecof** [bedna-KU/rtvs-dl#3]
Ahoj,

narazil som na tento skript ale uz nefunguje. Zmenila sa stranka RTVS archivu.
Myslim, ze by som to po chvilke skumania vedel fixnut ale ak by si mal naladu a cas, budes asi rychlejsi.

  hudecof

**Comment by bedna-KU** [comment]
Čau,
je to fixnuté, sorry že až teraz, nejak som prehliadol Issues.

Bedňa

**Comment by hudecof** [comment]
@bedna-KU vdaka
